(defun bubble-sort (lst)
  (labels ((bubble (lst)
             (cond ((null (cdr lst)) lst)
                   ((> (car lst) (cadr lst))
                    (cons (cadr lst) (bubble (cons (car lst) (cddr lst)))))
                   (t (cons (car lst) (bubble (cdr lst)))))))
    (let ((sorted t))
      (do ((new-lst lst (bubble new-lst)))
          ((eq sorted new-lst) new-lst)
        (setq sorted new-lst)))))
